name: seelang
description: An app to help you learn new languages.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  google_sign_in:
  firebase_auth: ^0.8.1
  firebase_ml_vision:
  firebase_storage:
  firebase_database:
  camera:
  path_provider:
  json_serializable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - images/logo.png
    - images/google-logo.png
